Repository 9JaHyun/munhwaya-nolja, pull requests merged in 2022-04, with the labels that each got.

#33 Music search back end job
  src/main/java/com/munhwa/prj/HomeController.java
  src/main/java/com/munhwa/prj/music/mapper/AlbumMapper.java
  src/main/java/com/munhwa/prj/music/mapper/MusicMapper.java
  src/main/java/com/munhwa/prj/music/mapper/PurchaseMapper.java
  src/main/java/com/munhwa/prj/music/mapper/album-map.xml
  src/main/java/com/munhwa/prj/music/mapper/music-map.xml
  src/main/java/com/munhwa/prj/music/mapper/purchase-map.xml
  src/main/java/com/munhwa/prj/music/service/AlbumService.java
  src/main/java/com/munhwa/prj/music/service/MusicService.java
  src/main/java/com/munhwa/prj/music/service/PurchaseService.java
  src/main/java/com/munhwa/prj/music/serviceImpl/AlbumServiceImpl.java
  src/main/java/com/munhwa/prj/music/serviceImpl/MusicServiceImpl.java
  src/main/java/com/munhwa/prj/music/serviceImpl/PurchaseServiceImpl.java
  src/main/java/com/munhwa/prj/music/vo/AlbumVO.java
  src/main/java/com/munhwa/prj/music/vo/PlayListVO.java
  src/main/java/com/munhwa/prj/music/vo/SearchVO.java
  src/main/java/com/munhwa/prj/music/web/MusicController.java
  src/main/webapp/WEB-INF/views/layout/layout.jsp
  src/main/webapp/WEB-INF/views/music/albumInfo.jsp
  src/main/webapp/WEB-INF/views/music/chart.jsp
  src/main/webapp/WEB-INF/views/music/genre.jsp
  src/main/webapp/WEB-INF/views/music/musicMain.jsp
  src/main/webapp/WEB-INF/views/music/personalResult.jsp
  src/main/webapp/WEB-INF/views/music/purchase.jsp
  src/main/webapp/WEB-INF/views/music/releaseSoon.jsp
  src/main/webapp/WEB-INF/views/music/searchResult.jsp
  src/main/webapp/WEB-INF/views/music/searchResultAlbum.jsp
  src/main/webapp/WEB-INF/views/music/searchResultMusic.jsp
  src/main/webapp/WEB-INF/views/music/streaming.jsp
  src/main/webapp/WEB-INF/views/music/streamingWishList.jsp
  src/main/webapp/resources/js/ttw-music-player-min.js
  src/main/webapp/resources/music/myplaylist.js
  src/main/webapp/resources/style.css
Labels: 💻 Feature, 🎨 HTML & CSS

#35 [Login] 로그인 기능 추가
  pom.xml
  src/main/java/com/munhwa/prj/HomeController.java
  src/main/java/com/munhwa/prj/common/api/FileClient.java
  src/main/java/com/munhwa/prj/config/auth/CustomCommonOAuth2Provider.java
  src/main/java/com/munhwa/prj/config/auth/LoginUser.java
  src/main/java/com/munhwa/prj/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/munhwa/prj/config/auth/OAuthAttributes.java
  src/main/java/com/munhwa/prj/config/auth/SecurityConfig.java
  src/main/java/com/munhwa/prj/config/auth/dto/SessionUser.java
  src/main/java/com/munhwa/prj/config/auth/handler/LoginFailureHandler.java
  src/main/java/com/munhwa/prj/config/auth/handler/LoginSuccessHandler.java
  src/main/java/com/munhwa/prj/config/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/munhwa/prj/config/auth/service/CustomOauth2UserService.java
  src/main/java/com/munhwa/prj/config/auth/service/LoginService.java
  src/main/java/com/munhwa/prj/member/mapper/MemberMapper.java
  src/main/java/com/munhwa/prj/member/mapper/member-map.xml
  src/main/java/com/munhwa/prj/member/service/MemberService.java
  src/main/java/com/munhwa/prj/member/serviceImpl/MemberServiceImpl.java
  src/main/java/com/munhwa/prj/member/vo/Auth.java
  src/main/java/com/munhwa/prj/member/vo/MemberVO.java
  src/main/java/com/munhwa/prj/member/web/LoginRequestDto.java
  src/main/java/com/munhwa/prj/member/web/MemberController.java
  src/main/java/com/munhwa/prj/music/web/MusicController.java
  src/main/java/com/munhwa/prj/performance/mapper/performance-map.xml
  src/main/java/com/munhwa/prj/ticketList/mapper/ticketlist-map.xml
  src/main/java/com/munhwa/prj/ticketList/web/TicketListController.java
  src/main/webapp/WEB-INF/spring/dataSource-context.xml
  src/main/webapp/WEB-INF/spring/servlet-context.xml
  src/main/webapp/WEB-INF/views/layout/header.jsp
  src/main/webapp/WEB-INF/views/layout/member-sidebar.jsp
  src/main/webapp/WEB-INF/views/session/sessionExpired.jsp
  src/main/webapp/WEB-INF/views/session/sessionList.jsp
  src/main/webapp/WEB-INF/views/session/sessions.jsp
  src/main/webapp/WEB-INF/views/signIn/signInForm.jsp
  src/main/webapp/WEB-INF/views/signup/signupForm.jsp
  src/main/webapp/WEB-INF/web.xml
Labels: 💻 Feature, 🎨 HTML & CSS

#36 Ticket list
  src/main/java/com/munhwa/prj/HomeController.java
  src/main/java/com/munhwa/prj/performance/mapper/PerformanceMapper.java
  src/main/java/com/munhwa/prj/performance/mapper/performance-map.xml
  src/main/java/com/munhwa/prj/performance/service/PerformanceService.java
  src/main/java/com/munhwa/prj/performance/serviceImpl/PerformanceServiceImpl.java
  src/main/java/com/munhwa/prj/performance/vo/Criteria.java
  src/main/java/com/munhwa/prj/performance/vo/PageMakeDTO.java
  src/main/java/com/munhwa/prj/performance/vo/PerformancePageVO.java
  src/main/java/com/munhwa/prj/performance/vo/PerformanceVO.java
  src/main/java/com/munhwa/prj/performance/web/PerformanceController.java
  src/main/java/com/munhwa/prj/ticketList/mapper/TicketListMapper.java
  src/main/java/com/munhwa/prj/ticketList/mapper/ticketlist-map.xml
  src/main/java/com/munhwa/prj/ticketList/service/TicketListService.java
  src/main/java/com/munhwa/prj/ticketList/serviceImpl/TicketListServiceImpl.java
  src/main/java/com/munhwa/prj/ticketList/web/TicketListController.java
  src/main/webapp/WEB-INF/views/performance/performance.jsp
  src/main/webapp/WEB-INF/views/performance/performanceInsertForm.jsp
  src/main/webapp/WEB-INF/views/performance/performanceList.jsp
  src/main/webapp/WEB-INF/views/performance/performanceSelect.jsp
  src/main/webapp/WEB-INF/views/ticketList/ticketList.jsp
  src/main/webapp/WEB-INF/views/ticketList/ticketListSelect.jsp
Labels: 💻 Feature, 🎨 HTML & CSS

#38 Mypage
  src/main/java/com/munhwa/prj/HomeController.java
  src/main/java/com/munhwa/prj/likeArtist/mapper/LikeArtistMapper.java
  src/main/java/com/munhwa/prj/likeArtist/mapper/likeArtist-map.xml
  src/main/java/com/munhwa/prj/likeArtist/service/LikeArtistService.java
  src/main/java/com/munhwa/prj/likeArtist/serviceImpl/LikeArtistServiceImpl.java
  src/main/java/com/munhwa/prj/likeArtist/vo/LikeArtistVO.java
  src/main/java/com/munhwa/prj/likeArtist/web/ArtistDeleteReqeustDto.java
  src/main/java/com/munhwa/prj/likeArtist/web/LikeArtistController.java
  src/main/java/com/munhwa/prj/member/mapper/MemberMapper.java
  src/main/java/com/munhwa/prj/member/mapper/member-map.xml
  src/main/java/com/munhwa/prj/member/service/MemberService.java
  src/main/java/com/munhwa/prj/member/serviceImpl/MemberServiceImpl.java
  src/main/java/com/munhwa/prj/member/web/MemberController.java
  src/main/java/com/munhwa/prj/news/mapper/NewsMapper.java
  src/main/java/com/munhwa/prj/news/mapper/news-map.xml
  src/main/java/com/munhwa/prj/news/service/NewsService.java
  src/main/java/com/munhwa/prj/news/serviceImpl/NewsServiceImpl.java
  src/main/java/com/munhwa/prj/news/vo/NewsVO.java
  src/main/java/com/munhwa/prj/news/web/NewsController.java
  src/main/java/com/munhwa/prj/wishlist/mapper/WishlistMapper.java
  src/main/java/com/munhwa/prj/wishlist/mapper/wishlist-map.xml
  src/main/java/com/munhwa/prj/wishlist/service/WishlistService.java
  src/main/java/com/munhwa/prj/wishlist/serviceImpl/WishlistServiceImpl.java
  src/main/java/com/munhwa/prj/wishlist/vo/WishlistMusicVO.java
  src/main/java/com/munhwa/prj/wishlist/vo/WishlistVO.java
  src/main/java/com/munhwa/prj/wishlist/web/WishlistController.java
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/layout/artist-sidebar.jsp
  src/main/webapp/WEB-INF/views/layout/artistLayout.jsp
  src/main/webapp/WEB-INF/views/layout/header.jsp
  src/main/webapp/WEB-INF/views/layout/member-sidebar.jsp
  src/main/webapp/WEB-INF/views/member/changeInfo.jsp
  src/main/webapp/WEB-INF/views/member/changePassword.jsp
  src/main/webapp/WEB-INF/views/member/changeProfile.jsp
  src/main/webapp/WEB-INF/views/member/dropMember.jsp
  src/main/webapp/WEB-INF/views/member/likeArtist.jsp
  src/main/webapp/WEB-INF/views/member/memberChangeInfo.jsp
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/WEB-INF/views/member/wishlist.jsp
  src/main/webapp/WEB-INF/views/member/wishlistMusic.jsp
  src/main/webapp/WEB-INF/views/signup/signupForm.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/resources/style.css
Labels: 💻 Feature, 🎨 HTML & CSS

#40 Streaming page button
  src/main/java/com/munhwa/prj/HomeController.java
  src/main/java/com/munhwa/prj/cart/web/CartController.java
  src/main/java/com/munhwa/prj/music/mapper/MusicMapper.java
  src/main/java/com/munhwa/prj/music/mapper/album-map.xml
  src/main/java/com/munhwa/prj/music/mapper/music-map.xml
  src/main/java/com/munhwa/prj/music/service/MusicService.java
  src/main/java/com/munhwa/prj/music/serviceImpl/MusicServiceImpl.java
  src/main/java/com/munhwa/prj/music/vo/PlayListVO.java
  src/main/java/com/munhwa/prj/music/web/MusicController.java
  src/main/java/com/munhwa/prj/wishlist/mapper/WishlistMapper.java
  src/main/java/com/munhwa/prj/wishlist/mapper/wishlist-map.xml
  src/main/java/com/munhwa/prj/wishlist/service/WishlistService.java
  src/main/java/com/munhwa/prj/wishlist/serviceImpl/WishlistServiceImpl.java
  src/main/java/com/munhwa/prj/wishlist/vo/WishlistVO.java
  src/main/java/com/munhwa/prj/wishlist/web/WishlistController.java
  src/main/webapp/WEB-INF/views/member/wishlist.jsp
  src/main/webapp/WEB-INF/views/member/wishlistMusic.jsp
  src/main/webapp/WEB-INF/views/music/albumInfo.jsp
  src/main/webapp/WEB-INF/views/music/chart.jsp
  src/main/webapp/WEB-INF/views/music/genre.jsp
  src/main/webapp/WEB-INF/views/music/musicMain.jsp
  src/main/webapp/WEB-INF/views/music/personalResult.jsp
  src/main/webapp/WEB-INF/views/music/searchResult.jsp
  src/main/webapp/WEB-INF/views/music/searchResultAlbum.jsp
  src/main/webapp/WEB-INF/views/music/searchResultMusic.jsp
  src/main/webapp/WEB-INF/views/music/streaming.jsp
  src/main/webapp/WEB-INF/views/music/streamingList.jsp
  src/main/webapp/WEB-INF/views/music/streamingWishList.jsp
  src/main/webapp/resources/js/ttw-music-player-min.js
Labels: 💻 Feature, 🎨 HTML & CSS

#48 Music page buttons
  src/main/java/com/munhwa/prj/HomeController.java
  src/main/java/com/munhwa/prj/cart/web/CartController.java
  src/main/java/com/munhwa/prj/common/api/FileClient.java
  src/main/java/com/munhwa/prj/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/munhwa/prj/member/mapper/member-map.xml
  src/main/java/com/munhwa/prj/member/serviceImpl/MemberServiceImpl.java
  src/main/java/com/munhwa/prj/member/vo/MemberVO.java
  src/main/java/com/munhwa/prj/member/web/MemberController.java
  src/main/java/com/munhwa/prj/music/mapper/AlbumMapper.java
  src/main/java/com/munhwa/prj/music/mapper/MusicMapper.java
  src/main/java/com/munhwa/prj/music/mapper/PurchaseMapper.java
  src/main/java/com/munhwa/prj/music/mapper/album-map.xml
  src/main/java/com/munhwa/prj/music/mapper/music-map.xml
  src/main/java/com/munhwa/prj/music/mapper/purchase-map.xml
  src/main/java/com/munhwa/prj/music/service/AlbumService.java
  src/main/java/com/munhwa/prj/music/service/MusicService.java
  src/main/java/com/munhwa/prj/music/service/PurchaseService.java
  src/main/java/com/munhwa/prj/music/serviceImpl/AlbumServiceImpl.java
  src/main/java/com/munhwa/prj/music/serviceImpl/MusicServiceImpl.java
  src/main/java/com/munhwa/prj/music/serviceImpl/PurchaseServiceImpl.java
  src/main/java/com/munhwa/prj/music/vo/MusicVO.java
  src/main/java/com/munhwa/prj/music/vo/PurchaseVO.java
  src/main/java/com/munhwa/prj/music/vo/PurchaseVO2.java
  src/main/java/com/munhwa/prj/music/vo/SearchVO.java
  src/main/java/com/munhwa/prj/music/vo/etc/MusicChartDto.java
  src/main/java/com/munhwa/prj/music/web/MusicController.java
  src/main/java/com/munhwa/prj/wallet/mapper/profit-map.xml
  src/main/java/com/munhwa/prj/wallet/mapper/usage-map.xml
  src/main/java/com/munhwa/prj/wishlist/mapper/WishlistMapper.java
  src/main/java/com/munhwa/prj/wishlist/mapper/wishlist-map.xml
  src/main/java/com/munhwa/prj/wishlist/service/WishlistService.java
  src/main/java/com/munhwa/prj/wishlist/serviceImpl/WishlistServiceImpl.java
  src/main/java/com/munhwa/prj/wishlist/web/WishlistController.java
  src/main/webapp/WEB-INF/views/member/changeInfo.jsp
  src/main/webapp/WEB-INF/views/member/changeProfile.jsp
  src/main/webapp/WEB-INF/views/member/likeArtist.jsp
  src/main/webapp/WEB-INF/views/member/memberChangeInfo.jsp
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/WEB-INF/views/member/wishlistMusic.jsp
  src/main/webapp/WEB-INF/views/music/albumInfo.jsp
  src/main/webapp/WEB-INF/views/music/chart.jsp
  src/main/webapp/WEB-INF/views/music/chicken.jsp
  src/main/webapp/WEB-INF/views/music/genre.jsp
  src/main/webapp/WEB-INF/views/music/musicMain.jsp
  src/main/webapp/WEB-INF/views/music/personalResult.jsp
  src/main/webapp/WEB-INF/views/music/purchase.jsp
  src/main/webapp/WEB-INF/views/music/releaseSoon.jsp
  src/main/webapp/WEB-INF/views/music/searchResult.jsp
  src/main/webapp/WEB-INF/views/music/searchResultAlbum.jsp
  src/main/webapp/WEB-INF/views/music/searchResultMusic.jsp
  src/main/webapp/WEB-INF/views/music/streaming.jsp
  src/main/webapp/WEB-INF/views/music/streamingList.jsp
  src/main/webapp/WEB-INF/views/music/streamingWishList.jsp
  src/main/webapp/resources/images/bg/musicBB.jpg
  src/main/webapp/resources/js/ttw-music-player-min.js
Labels: 💻 Feature, 🎨 HTML & CSS

#51 Mapapi
  src/main/java/com/munhwa/prj/admin/web/AdminController.java
  src/main/java/com/munhwa/prj/artist/mapper/artist-map.xml
  src/main/java/com/munhwa/prj/member/mapper/member-map.xml
  src/main/java/com/munhwa/prj/performance/mapper/PerformanceMapper.java
  src/main/java/com/munhwa/prj/performance/mapper/performance-map.xml
  src/main/java/com/munhwa/prj/performance/service/PerformanceService.java
  src/main/java/com/munhwa/prj/performance/serviceImpl/PerformanceServiceImpl.java
  src/main/java/com/munhwa/prj/performance/vo/PerformancePersonalVO.java
  src/main/java/com/munhwa/prj/performance/vo/PerformanceVO.java
  src/main/java/com/munhwa/prj/performance/web/PerformanceController.java
  src/main/java/com/munhwa/prj/ticketList/mapper/TicketListMapper.java
  src/main/java/com/munhwa/prj/ticketList/mapper/ticketlist-map.xml
  src/main/java/com/munhwa/prj/ticketList/service/TicketListService.java
  src/main/java/com/munhwa/prj/ticketList/serviceImpl/TicketListServiceImpl.java
  src/main/java/com/munhwa/prj/ticketList/vo/TicketListVO.java
  src/main/java/com/munhwa/prj/ticketList/web/TicketListController.java
  src/main/java/com/munhwa/prj/wallet/mapper/profit-map.xml
  src/main/java/com/munhwa/prj/wallet/mapper/usage-map.xml
  src/main/java/com/munhwa/prj/wallet/vo/ProfitVO.java
  src/main/java/com/munhwa/prj/wallet/vo/UsageVO.java
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/admin/adminPerformanceList.jsp
  src/main/webapp/WEB-INF/views/layout/header.jsp
  src/main/webapp/WEB-INF/views/performance/performance.jsp
  src/main/webapp/WEB-INF/views/performance/performanceInsertForm.jsp
  src/main/webapp/WEB-INF/views/performance/performanceList.jsp
  src/main/webapp/WEB-INF/views/performance/performanceSelect.jsp
  src/main/webapp/WEB-INF/views/qrcode/kakaotest.jsp
  src/main/webapp/WEB-INF/views/qrcode/qrcodeDetail.jsp
  src/main/webapp/WEB-INF/views/qrcode/qrcodeError.jsp
  src/main/webapp/WEB-INF/views/ticketList/ticketList.jsp
  src/main/webapp/WEB-INF/views/ticketList/ticketListSelect.jsp
Labels: 💻 Feature, 🎨 HTML & CSS

#52 Music page style
  src/main/java/com/munhwa/prj/cart/web/CartController.java
  src/main/java/com/munhwa/prj/music/mapper/MusicMapper.java
  src/main/java/com/munhwa/prj/music/mapper/album-map.xml
  src/main/java/com/munhwa/prj/music/mapper/music-map.xml
  src/main/java/com/munhwa/prj/music/mapper/purchase-map.xml
  src/main/java/com/munhwa/prj/music/service/MusicService.java
  src/main/java/com/munhwa/prj/music/serviceImpl/MusicServiceImpl.java
  src/main/java/com/munhwa/prj/music/vo/PurchaseVO2.java
  src/main/java/com/munhwa/prj/music/web/MusicController.java
  src/main/java/com/munhwa/prj/wallet/mapper/usage-map.xml
  src/main/java/com/munhwa/prj/wallet/vo/ProfitVO.java
  src/main/java/com/munhwa/prj/wallet/web/WalletController.java
  src/main/webapp/WEB-INF/views/music/albumInfo.jsp
  src/main/webapp/WEB-INF/views/music/chart.jsp
  src/main/webapp/WEB-INF/views/music/genre.jsp
  src/main/webapp/WEB-INF/views/music/musicMain.jsp
  src/main/webapp/WEB-INF/views/music/personalResult.jsp
  src/main/webapp/WEB-INF/views/music/purchase.jsp
  src/main/webapp/WEB-INF/views/music/releaseSoon.jsp
  src/main/webapp/WEB-INF/views/music/searchResult.jsp
  src/main/webapp/WEB-INF/views/music/searchResultAlbum.jsp
  src/main/webapp/WEB-INF/views/music/searchResultMusic.jsp
  src/main/webapp/WEB-INF/views/music/streaming.jsp
  src/main/webapp/WEB-INF/views/music/streamingList.jsp
  src/main/webapp/WEB-INF/views/music/streamingWishList.jsp
Labels: 💻 Feature, 🎨 HTML & CSS

#53 Cart5
  src/main/java/com/munhwa/prj/cart/web/CartController.java
  src/main/java/com/munhwa/prj/music/mapper/purchase-map.xml
  src/main/webapp/WEB-INF/views/cart/shop_cart.jsp
  src/main/webapp/WEB-INF/views/layout/member-sidebar.jsp
  src/main/webapp/WEB-INF/views/music/chart.jsp
  src/main/webapp/WEB-INF/views/wallet/profitHistoryOfMusic.jsp
  src/main/webapp/WEB-INF/views/wallet/profitHistoryOfPerformance.jsp
  src/main/webapp/WEB-INF/views/wallet/usageHistoryOfMusic.jsp
  src/main/webapp/WEB-INF/views/wallet/usageHistoryOfPerformance.jsp
  src/main/webapp/WEB-INF/views/wallet/walletInfoSelect.jsp
Labels: 💻 Feature, 🎨 HTML & CSS

#54 Mypage2
  src/main/java/com/munhwa/prj/artist/mapper/ArtistMapper.java
  src/main/java/com/munhwa/prj/artist/mapper/artist-map.xml
  src/main/java/com/munhwa/prj/artist/service/ArtistService.java
  src/main/java/com/munhwa/prj/artist/serviceImpl/ArtistServiceImpl.java
  src/main/java/com/munhwa/prj/member/mapper/MemberMapper.java
  src/main/java/com/munhwa/prj/member/mapper/member-map.xml
  src/main/java/com/munhwa/prj/member/web/MemberController.java
  src/main/java/com/munhwa/prj/news/mapper/NewsMapper.java
  src/main/java/com/munhwa/prj/news/mapper/news-map.xml
  src/main/java/com/munhwa/prj/news/service/NewsService.java
  src/main/java/com/munhwa/prj/news/serviceImpl/NewsServiceImpl.java
  src/main/java/com/munhwa/prj/news/web/NewsController.java
  src/main/webapp/WEB-INF/views/home/home.jsp
  src/main/webapp/WEB-INF/views/layout/footer.jsp
  src/main/webapp/WEB-INF/views/member/changeProfile.jsp
  src/main/webapp/WEB-INF/views/member/likeArtist.jsp
  src/main/webapp/WEB-INF/views/member/memberChangeInfo.jsp
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/WEB-INF/views/member/wishlist.jsp
  src/main/webapp/WEB-INF/views/signup/signupForm.jsp
Labels: 💻 Feature, 🎨 HTML & CSS

#55 Artist2
  src/main/java/com/munhwa/prj/admin/web/ArtistChangeRequestDto.java
  src/main/java/com/munhwa/prj/artist/mapper/ArtistMapper.java
  src/main/java/com/munhwa/prj/artist/mapper/artist-map.xml
  src/main/java/com/munhwa/prj/artist/service/ArtistService.java
  src/main/java/com/munhwa/prj/artist/serviceImpl/ArtistServiceImpl.java
  src/main/java/com/munhwa/prj/artist/vo/ArtistVO.java
  src/main/java/com/munhwa/prj/artist/web/ArtistController.java
  src/main/java/com/munhwa/prj/common/entity/UploadFile.java
  src/main/webapp/WEB-INF/views/artist/artistDetail.jsp
  src/main/webapp/WEB-INF/views/artist/artistProfile.jsp
  src/main/webapp/WEB-INF/views/artist/artistRequest.jsp
  src/main/webapp/WEB-INF/views/artist/changeArtistProfile.jsp
  src/main/webapp/WEB-INF/views/layout/member-sidebar.jsp
  src/main/webapp/WEB-INF/views/member/memberChangeInfo.jsp
  src/main/webapp/resources/images/artistFile/20945586-f7f1-43ab-9e11-cb614d3347ec.png
  src/main/webapp/resources/images/artistFile/282f586a-fd7a-43eb-a41b-3d09123399e3.png
  src/main/webapp/resources/images/artistFile/2e193b64-b469-4b0e-b634-ac1ce3001681.png
  src/main/webapp/resources/images/artistFile/3c90870e-9e52-4d80-845b-997459a24470.png
  src/main/webapp/resources/images/artistFile/4324db97-4f5d-4a24-9b5f-660f2b4777c9.png
  src/main/webapp/resources/images/artistFile/4f133fb3-5661-494e-bcb4-e5fd44696c78.png
  src/main/webapp/resources/images/artistFile/6e3b7668-2ddb-4721-a148-94812e602c3b.png
  src/main/webapp/resources/images/artistFile/7015869f-0ec7-4fc3-8496-3951f685c0b0.properties
  src/main/webapp/resources/images/artistFile/7b8e360b-5260-4f18-93b5-d25d40a1c840.png
  src/main/webapp/resources/images/artistFile/856de1d1-9781-4ef3-ba6f-c9e9ca627289.png
  src/main/webapp/resources/images/artistFile/95f23a0e-f589-46a6-83b7-baa4c038281b.jpg
  src/main/webapp/resources/images/artistFile/adc19042-403a-49ae-9033-d8cbe0b8d679.png
  src/main/webapp/resources/images/artistFile/bcbd262e-0afe-48fe-a5d7-34106619c882.png
  src/main/webapp/resources/images/artistFile/c3fed3b8-ea00-48d4-bea7-4f19767358a6.png
  src/main/webapp/resources/images/artistFile/c607f9c2-316f-423a-ac83-0ac412e86130.properties
  src/main/webapp/resources/images/artistFile/click.png
  src/main/webapp/resources/images/artistFile/db.properties
  src/main/webapp/resources/images/artistFile/e3a01360-4d3e-4f50-9d2c-fedcdb168249.png
  src/main/webapp/resources/images/artistFile/fa6ce07c-54b7-4b50-ac7d-32ea624e74b8.jpg
Labels: 💻 Feature, 🎨 HTML & CSS

#56 Artist controller 수정
  src/main/java/com/munhwa/prj/artist/mapper/ArtistMapper.java
  src/main/java/com/munhwa/prj/artist/mapper/PromotionRequestMapper.java
  src/main/java/com/munhwa/prj/artist/mapper/artist-map.xml
  src/main/java/com/munhwa/prj/artist/mapper/promotionRequest-map.xml
  src/main/java/com/munhwa/prj/artist/service/ArtistService.java
  src/main/java/com/munhwa/prj/artist/serviceImpl/ArtistServiceImpl.java
  src/main/java/com/munhwa/prj/artist/serviceImpl/SmsServiceImpl.java
  src/main/java/com/munhwa/prj/artist/web/ArtistController.java
  src/main/java/com/munhwa/prj/common/api/FileClient.java
  src/main/java/com/munhwa/prj/member/web/MemberController.java
  src/main/java/com/munhwa/prj/music/web/MusicController.java
  src/main/java/com/munhwa/prj/performance/web/PerformanceController.java
  src/main/java/com/munhwa/prj/ticketList/web/TicketListController.java
  src/main/java/com/munhwa/prj/wishlist/web/WishlistController.java
Labels: 💻 Feature, 🎨 HTML & CSS

#57 Refactoring
  src/main/java/com/munhwa/prj/artist/serviceImpl/SmsServiceImpl.java
  src/main/java/com/munhwa/prj/artist/web/ArtistController.java
  src/main/java/com/munhwa/prj/artist/web/ArtistRequestDTO.java
  src/main/java/com/munhwa/prj/charge/mapper/ChargeMapper.java
  src/main/java/com/munhwa/prj/charge/mapper/charge-map.xml
  src/main/java/com/munhwa/prj/charge/service/ChargeService.java
  src/main/java/com/munhwa/prj/charge/serviceImpl/ChargeServiceImpl.java
  src/main/java/com/munhwa/prj/charge/vo/ChargeVO.java
  src/main/java/com/munhwa/prj/common/code/entity/CommonCodeVO.java
  src/main/java/com/munhwa/prj/common/code/entity/Genre.java
  src/main/java/com/munhwa/prj/common/entity/AmountChangeRequestDTO.java
  src/main/java/com/munhwa/prj/common/file/api/FileClient.java
  src/main/java/com/munhwa/prj/common/file/entity/UploadFile.java
  src/main/java/com/munhwa/prj/common/file/entity/UploadFileVO.java
  src/main/java/com/munhwa/prj/common/file/mapper/UploadFileMapper.java
  src/main/java/com/munhwa/prj/common/file/mapper/uploadFile-map.xml
  src/main/java/com/munhwa/prj/common/file/service/FileUtils.java
  src/main/java/com/munhwa/prj/common/file/service/UploadFileService.java
  src/main/java/com/munhwa/prj/common/file/serviceImpl/UploadFileServiceImpl.java
  src/main/java/com/munhwa/prj/common/paging/entity/Criteria.java
  src/main/java/com/munhwa/prj/common/paging/entity/PageDTO.java
  src/main/java/com/munhwa/prj/common/propertyScan/service/PropertiesScan.java
  src/main/java/com/munhwa/prj/config/auth/SecurityConfig.java
  src/main/java/com/munhwa/prj/config/auth/dto/SessionUser.java
  src/main/java/com/munhwa/prj/config/auth/service/CustomOauth2UserService.java
  src/main/java/com/munhwa/prj/member/mapper/MemberMapper.java
  src/main/java/com/munhwa/prj/member/mapper/member-map.xml
  src/main/java/com/munhwa/prj/member/service/MemberService.java
  src/main/java/com/munhwa/prj/member/serviceImpl/MemberServiceImpl.java
  src/main/java/com/munhwa/prj/member/web/MemberController.java
  src/main/java/com/munhwa/prj/music/mapper/AlbumMapper.java
  src/main/java/com/munhwa/prj/music/mapper/MusicMapper.java
  src/main/java/com/munhwa/prj/music/mapper/PurchaseMapper.java
  src/main/java/com/munhwa/prj/music/service/AlbumService.java
  src/main/java/com/munhwa/prj/music/service/MusicService.java
  src/main/java/com/munhwa/prj/music/service/PurchaseService.java
  src/main/java/com/munhwa/prj/music/serviceImpl/AlbumServiceImpl.java
  src/main/java/com/munhwa/prj/music/serviceImpl/MusicServiceImpl.java
  src/main/java/com/munhwa/prj/music/serviceImpl/PurchaseServiceImpl.java
  src/main/java/com/munhwa/prj/music/web/MusicController.java
  src/main/java/com/munhwa/prj/performance/web/PerformanceController.java
  src/main/java/com/munhwa/prj/wallet/mapper/ProfitMapper.java
  src/main/java/com/munhwa/prj/wallet/mapper/UsageMapper.java
  src/main/java/com/munhwa/prj/wallet/mapper/profit-map.xml
  src/main/java/com/munhwa/prj/wallet/mapper/usage-map.xml
  src/main/java/com/munhwa/prj/wallet/service/ProfitService.java
  src/main/java/com/munhwa/prj/wallet/service/UsageService.java
  src/main/java/com/munhwa/prj/wallet/serviceImpl/ProfitServiceImpl.java
  src/main/java/com/munhwa/prj/wallet/serviceImpl/UsageServiceImpl.java
  src/main/java/com/munhwa/prj/wallet/vo/ProfitVO.java
  src/main/java/com/munhwa/prj/wallet/vo/UsageVO.java
  src/main/java/com/munhwa/prj/wallet/web/WalletController.java
  src/main/webapp/WEB-INF/views/member/changeProfile.jsp
  src/main/webapp/WEB-INF/views/signup/signupForm.jsp
Labels: 🔨 Refactor

#58 [event] merge to develop
  src/main/java/com/munhwa/prj/admin/web/AdminController.java
  src/main/java/com/munhwa/prj/likeArtist/mapper/LikeArtistMapper.java
  src/main/java/com/munhwa/prj/likeArtist/mapper/likeArtist-map.xml
  src/main/java/com/munhwa/prj/likeArtist/service/LikeArtistService.java
  src/main/java/com/munhwa/prj/likeArtist/serviceImpl/LikeArtistServiceImpl.java
  src/main/java/com/munhwa/prj/member/web/MemberController.java
  src/main/java/com/munhwa/prj/news/event/AlbumRequestHandler.java
  src/main/java/com/munhwa/prj/news/event/PerformanceRequestHandler.java
  src/main/java/com/munhwa/prj/news/event/entity/AlbumRequestEvent.java
  src/main/java/com/munhwa/prj/news/event/entity/PerformancePublishEvent.java
  src/main/java/com/munhwa/prj/news/mapper/NewsMapper.java
  src/main/java/com/munhwa/prj/news/mapper/news-map.xml
  src/main/java/com/munhwa/prj/news/service/NewsService.java
  src/main/java/com/munhwa/prj/news/serviceImpl/NewsServiceImpl.java
  src/main/java/com/munhwa/prj/news/vo/NewsVO.java
  src/main/java/com/munhwa/prj/news/web/NewsController.java
  src/main/java/com/munhwa/prj/performance/mapper/performance-map.xml
Labels: 💻 Feature

#59 Cart6
  src/main/java/com/munhwa/prj/member/mapper/member-map.xml
  src/main/java/com/munhwa/prj/music/mapper/purchase-map.xml
  src/main/java/com/munhwa/prj/ticketList/web/TicketListController.java
  src/main/java/com/munhwa/prj/wallet/mapper/UsageMapper.java
  src/main/java/com/munhwa/prj/wallet/mapper/profit-map.xml
  src/main/java/com/munhwa/prj/wallet/mapper/usage-map.xml
  src/main/java/com/munhwa/prj/wallet/service/UsageService.java
  src/main/java/com/munhwa/prj/wallet/serviceImpl/UsageServiceImpl.java
  src/main/java/com/munhwa/prj/wallet/vo/ArtistVO.java
  src/main/java/com/munhwa/prj/wallet/vo/ProfitVO.java
  src/main/java/com/munhwa/prj/wallet/vo/UsageVO.java
  src/main/java/com/munhwa/prj/wallet/web/RefundRequestDto.java
  src/main/java/com/munhwa/prj/wallet/web/WalletController.java
  src/main/webapp/WEB-INF/views/layout/member-sidebar.jsp
  src/main/webapp/WEB-INF/views/wallet/chargeForm.jsp
  src/main/webapp/WEB-INF/views/wallet/profitHistoryOfMusic.jsp
  src/main/webapp/WEB-INF/views/wallet/profitHistoryOfPerformance.jsp
  src/main/webapp/WEB-INF/views/wallet/usageHistoryOfMusic.jsp
  src/main/webapp/WEB-INF/views/wallet/usageHistoryOfPerformance.jsp
Labels: 💻 Feature

#61 [MusicTest}
  src/main/java/com/munhwa/prj/wishlist/mapper/wishlist-map.xml
  src/main/java/com/munhwa/prj/wishlist/vo/WishlistMusicVO.java
  src/main/webapp/WEB-INF/views/music/purchase.jsp
Labels: 💻 Feature

#62 출금기능 1차 merge
  src/main/java/com/munhwa/prj/HomeController.java
  src/main/java/com/munhwa/prj/withdraw/api/OpenBankApiClient.java
  src/main/java/com/munhwa/prj/withdraw/api/OpenBankutil.java
  src/main/java/com/munhwa/prj/withdraw/configuration/Config.java
  src/main/java/com/munhwa/prj/withdraw/dto/AccountSearchRequestDto.java
  src/main/java/com/munhwa/prj/withdraw/dto/AccountTransferRequestDto.java
  src/main/java/com/munhwa/prj/withdraw/dto/AccountTransferResponseDto.java
  src/main/java/com/munhwa/prj/withdraw/dto/AcountDto.java
  src/main/java/com/munhwa/prj/withdraw/dto/AuthorizationRequestDto.java
  src/main/java/com/munhwa/prj/withdraw/dto/AuthorizationResponseDto.java
  src/main/java/com/munhwa/prj/withdraw/dto/BankAcountSearchResponseDto.java
  src/main/java/com/munhwa/prj/withdraw/dto/BankBalanceRequestDto.java
  src/main/java/com/munhwa/prj/withdraw/dto/BankBalanceResponseDto.java
  src/main/java/com/munhwa/prj/withdraw/dto/BankReponseToken.java
  src/main/java/com/munhwa/prj/withdraw/dto/BankRequestToken.java
  src/main/java/com/munhwa/prj/withdraw/dto/CodeRequestDTO.java
  src/main/java/com/munhwa/prj/withdraw/dto/CodeResponseDTO.java
  src/main/java/com/munhwa/prj/withdraw/dto/RealNameRequestDTO.java
  src/main/java/com/munhwa/prj/withdraw/dto/RealNameResponseDTO.java
  src/main/java/com/munhwa/prj/withdraw/dto/TokenRequestDTO.java
  src/main/java/com/munhwa/prj/withdraw/dto/TokenResponseDTO.java
  src/main/java/com/munhwa/prj/withdraw/dto/User.java
  src/main/java/com/munhwa/prj/withdraw/service/OpenBankService.java
  src/main/java/com/munhwa/prj/withdraw/web/OpenBankApiController.java
  src/main/java/com/munhwa/prj/withdraw/web/WithdrawController.java
  src/main/webapp/WEB-INF/spring/appServlet/dataSource-context.xml
  src/main/webapp/WEB-INF/views/withdraw/accountList.html
  src/main/webapp/WEB-INF/views/withdraw/accountList.jsp
  src/main/webapp/WEB-INF/views/withdraw/balance.html
  src/main/webapp/WEB-INF/views/withdraw/balance.jsp
  src/main/webapp/WEB-INF/views/withdraw/bank.html
  src/main/webapp/WEB-INF/views/withdraw/bank.jsp
  src/main/webapp/WEB-INF/views/withdraw/home.html
  src/main/webapp/WEB-INF/views/withdraw/home.jsp
  src/main/webapp/WEB-INF/views/withdraw/transferForm.html
  src/main/webapp/WEB-INF/views/withdraw/transferForm.jsp
  src/main/webapp/WEB-INF/views/withdraw/withdraw.jsp
Labels: 💻 Feature, 🎨 HTML & CSS

#81 Music test2
  src/main/java/com/munhwa/prj/artist/mapper/ArtistMapper.java
  src/main/java/com/munhwa/prj/artist/mapper/artist-map.xml
  src/main/java/com/munhwa/prj/artist/service/ArtistService.java
  src/main/java/com/munhwa/prj/artist/serviceImpl/ArtistServiceImpl.java
  src/main/java/com/munhwa/prj/cart/web/CartController.java
  src/main/java/com/munhwa/prj/music/mapper/music-map.xml
  src/main/java/com/munhwa/prj/music/mapper/purchase-map.xml
  src/main/java/com/munhwa/prj/music/vo/PurchaseVO2.java
  src/main/java/com/munhwa/prj/music/vo/etc/MusicChartDto.java
  src/main/java/com/munhwa/prj/music/web/MusicController.java
  src/main/webapp/WEB-INF/spring/dataSource-context.xml
  src/main/webapp/WEB-INF/views/music/albumInfo.jsp
  src/main/webapp/WEB-INF/views/music/chart.jsp
  src/main/webapp/WEB-INF/views/music/chicken.jsp
  src/main/webapp/WEB-INF/views/music/genre.jsp
  src/main/webapp/WEB-INF/views/music/personalResult.jsp
  src/main/webapp/WEB-INF/views/music/purchase.jsp
  src/main/webapp/WEB-INF/views/music/releaseSoon.jsp
  src/main/webapp/WEB-INF/views/music/searchResult.jsp
  src/main/webapp/WEB-INF/views/music/searchResultMusic.jsp
  src/main/webapp/WEB-INF/views/music/streaming.jsp
Labels: 💻 Feature, 🎨 HTML & CSS

#86 Wallet list
  src/main/java/com/munhwa/prj/cart/web/CartController.java
  src/main/java/com/munhwa/prj/charge/mapper/charge-map.xml
  src/main/java/com/munhwa/prj/music/mapper/PurchaseMapper.java
  src/main/java/com/munhwa/prj/music/mapper/purchase-map.xml
  src/main/java/com/munhwa/prj/music/service/PurchaseService.java
  src/main/java/com/munhwa/prj/music/serviceImpl/MusicServiceImpl.java
  src/main/java/com/munhwa/prj/music/serviceImpl/PurchaseServiceImpl.java
  src/main/java/com/munhwa/prj/wallet/mapper/UsageMapper.java
  src/main/java/com/munhwa/prj/wallet/mapper/profit-map.xml
  src/main/java/com/munhwa/prj/wallet/mapper/usage-map.xml
  src/main/java/com/munhwa/prj/wallet/service/UsageService.java
  src/main/java/com/munhwa/prj/wallet/serviceImpl/UsageServiceImpl.java
  src/main/java/com/munhwa/prj/wallet/vo/UsageVO.java
  src/main/java/com/munhwa/prj/wallet/web/WalletController.java
  src/main/resources/config/db.properties
  src/main/webapp/WEB-INF/spring/appServlet/dataSource-context.xml
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/admin/judgeArtist.jsp
  src/main/webapp/WEB-INF/views/cart/shop_cart.jsp
  src/main/webapp/WEB-INF/views/wallet/chargeForm.jsp
  src/main/webapp/WEB-INF/views/wallet/profitHistoryOfMusic.jsp
  src/main/webapp/WEB-INF/views/wallet/profitHistoryOfPerformance.jsp
  src/main/webapp/WEB-INF/views/wallet/usageHistoryOfMusic.jsp
  src/main/webapp/WEB-INF/views/wallet/usageHistoryOfPerformance.jsp
  src/main/webapp/WEB-INF/views/wallet/walletInfo.jsp
  src/main/webapp/WEB-INF/views/wallet/walletInfoSelect.jsp
Labels: 💻 Feature, 🎨 HTML & CSS
